// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCObagG7DklXPDWYEAuVVQg2YFJrID6-Jg',
    appId: '1:870519253162:web:08488990c9c0cf010308d3',
    messagingSenderId: '870519253162',
    projectId: 'hadir-app-d5cfb',
    authDomain: 'hadir-app-d5cfb.firebaseapp.com',
    storageBucket: 'hadir-app-d5cfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn--fpRxlsyc3zd4VtvZFZI-XrY-Irkpw',
    appId: '1:870519253162:android:ebcd2193bb387d310308d3',
    messagingSenderId: '870519253162',
    projectId: 'hadir-app-d5cfb',
    storageBucket: 'hadir-app-d5cfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEW_W4lpj-wF0gq2U9HOKHjJ1ir6txFlA',
    appId: '1:870519253162:ios:d414cf84919849280308d3',
    messagingSenderId: '870519253162',
    projectId: 'hadir-app-d5cfb',
    storageBucket: 'hadir-app-d5cfb.firebasestorage.app',
    iosBundleId: 'com.example.attendace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEW_W4lpj-wF0gq2U9HOKHjJ1ir6txFlA',
    appId: '1:870519253162:ios:d414cf84919849280308d3',
    messagingSenderId: '870519253162',
    projectId: 'hadir-app-d5cfb',
    storageBucket: 'hadir-app-d5cfb.firebasestorage.app',
    iosBundleId: 'com.example.attendace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCObagG7DklXPDWYEAuVVQg2YFJrID6-Jg',
    appId: '1:870519253162:web:fd89ffd8b0b554fc0308d3',
    messagingSenderId: '870519253162',
    projectId: 'hadir-app-d5cfb',
    authDomain: 'hadir-app-d5cfb.firebaseapp.com',
    storageBucket: 'hadir-app-d5cfb.firebasestorage.app',
  );
}
